name: ${DOCKER_APP_NAME}

services:
  database:
    container_name: ${DOCKER_CONTAINER_NAME_DB}
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - dev_network

  redis:
    image: redis:7
    container_name: ${DOCKER_CONTAINER_NAME_REDIS}
    platform: linux/arm64/v8
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    command:
      [
        "redis-server",
        "--maxmemory-policy",
        "noeviction",
        "--ignore-warnings",
        "ARM64-COW-BUG",
      ]
    networks:
      - dev_network

networks:
  dev_network:
